version: "3.9"

services:
  novnc:
    image: ifrstr/novnc:0.0.2

    # Or build locally
    # build: .

    security_opt:
      - seccomp:unconfined

    deploy:
      restart_policy:
        condition: on-failure

    ports:
      - "80:80"
      - "5901:5901"
